import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F8F8F8",
        paddingHorizontal: 16,
        paddingTop: 20,
    },
    totalCard: {
        backgroundColor: "#00907a",
        borderRadius: 8,
        padding: 16,
        alignItems: "center",
        marginBottom: 20,
    },
    totalText: {
        fontSize: 16,
        color: "#FFF",
        fontWeight: "bold",
        marginBottom: 8,
    },
    totalValor: {
        fontSize: 24,
        color: "#FFF",
        fontWeight: "bold",
    },
    filterButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#FFF",
        padding: 10,
        borderRadius: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
        marginBottom: 20,
    },
    filterButtonText: {
        marginLeft: 8,
        color: "#00907a",
        fontWeight: "bold",
        fontSize: 16,
    },
    removeFilterButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#ff4d4d",
        padding: 10,
        borderRadius: 8,
        marginBottom: 10,
    },
    removeFilterButtonText: {
        marginLeft: 8,
        color: "#FFF",
        fontWeight: "bold",
        fontSize: 16,
    },
    rangeText: {
        color: "#707070",
        fontSize: 14,
        textAlign: "center",
        marginBottom: 10,
    },
    transacaoItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFF",
        padding: 12,
        borderRadius: 8,
        marginBottom: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    transacaoData: {
        fontSize: 14,
        color: "#707070",
        flex: 1,
        textAlign: "center",
    },
    separator: {
        fontSize: 16,
        color: "#C0C0C0",
        marginHorizontal: 8,
    },
    transacaoParceiro: {
        fontSize: 14,
        color: "#00907a",
        fontWeight: "bold",
        flex: 2,
        textAlign: "center",
    },
    transacaoPontos: {
        fontSize: 14,
        color: "#00907a",
        fontWeight: "bold",
        flex: 1,
        textAlign: "center",
    },
    transacaoList: {
        paddingBottom: 20,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalContent: {
        width: "90%",
        backgroundColor: "#FFF",
        borderRadius: 10,
        padding: 20,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    filterTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#00907a",
        marginBottom: 20,
    },
    closeButton: {
        marginTop: 20,
        backgroundColor: "#00907a",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    closeButtonText: {
        color: "#FFF",
        fontSize: 16,
        fontWeight: "bold",
    },
});
