import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: '#00907a',
        alignItems: 'center',
    },
    trophy: {
        marginTop: -30,
        width: 250,
        height: 250,
    },
    loader: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#f4f4f8",
    },
    dateText: {
        fontSize: 18,
        color: "#fff",
        fontWeight: 'bold',
        marginBottom: 12,
        textAlign: 'center'
    },
    rankingList: {
        paddingBottom: 40,
    },
    card: {
        backgroundColor: "#ffffff",
        borderRadius: 10,
        paddingVertical: 12,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 8,
        width: "100%",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    position: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#333",
        width: 40,
        textAlign: "center",
    },
    name: {
        fontSize: 15,
        color: "#333",
        flex: 1,
        textAlign: "left",
        paddingHorizontal: 10,
    },
    points: {
        fontSize: 15,
        fontWeight: "600",
        color: "#333",
        width: 80,
        textAlign: "right",
    },
    totalCard: {
        backgroundColor: "#fff",
        padding: 20,
        borderRadius: 10,
        alignItems: "center",
        marginBottom: 20,
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 4,
    },
    totalText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    totalPeso: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#00907a',
    },
});
